# See https://docs.github.com/en/github/administering-a-repository/enabling-and-disabling-version-updates

version: 2
updates:

  - package-ecosystem: "gomod"
    open-pull-requests-limit: 2
    directory: "/hack/update-go-mod"
    schedule:
      interval: "daily"

  # Use dependabot to automate major-only dependency bumps
  - package-ecosystem: "gomod"
    open-pull-requests-limit: 2 # Not sure why there would ever be more than 1, just would not want to hide anything
    directory: "/"
    schedule:
      interval: "daily"
    # group all major dependency bumps together so there's only one pull request
    groups:
      go-modules:
        patterns:
        - "*"
        update-types:
        - "major"
    ignore:
    # For all packages, ignore all minor and patch updates
    - dependency-name: "*"
      update-types:
      - "version-update:semver-minor"
      - "version-update:semver-patch"

# Our own CI job is responsible for updating this Docker file now.
#  - package-ecosystem: "docker"
#    directory: "/"
#    schedule:
#      interval: "daily"

# Our own CI job is responsible for updating this Docker file now.
#  - package-ecosystem: "docker"
#    directory: "/hack"  # this should keep the FIPS dockerfile updated per https://github.com/dependabot/feedback/issues/145#issuecomment-414738498
#    schedule:
#      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/dockerfiles/code-coverage-uploader/"
    open-pull-requests-limit: 100
    schedule:
      interval: "daily"
    target-branch: ci
  - package-ecosystem: "docker"
    directory: "/dockerfiles/crane/"
    open-pull-requests-limit: 100
    schedule:
      interval: "daily"
    target-branch: ci
  - package-ecosystem: "docker"
    directory: "/dockerfiles/deployment-yaml-formatter/"
    open-pull-requests-limit: 100
    schedule:
      interval: "daily"
    target-branch: ci
  - package-ecosystem: "docker"
    directory: "/dockerfiles/eks-deployer/"
    open-pull-requests-limit: 100
    schedule:
      interval: "daily"
    target-branch: ci
  - package-ecosystem: "docker"
    directory: "/dockerfiles/gh-cli/"
    open-pull-requests-limit: 100
    schedule:
      interval: "daily"
    target-branch: ci
  - package-ecosystem: "docker"
    directory: "/dockerfiles/integration-test-runner/"
    open-pull-requests-limit: 100
    schedule:
      interval: "daily"
    target-branch: ci
  - package-ecosystem: "docker"
    directory: "/dockerfiles/integration-test-runner-beta/"
    open-pull-requests-limit: 100
    schedule:
      interval: "daily"
    target-branch: ci
  - package-ecosystem: "docker"
    directory: "/dockerfiles/k8s-app-deployer/"
    open-pull-requests-limit: 100
    schedule:
      interval: "daily"
    target-branch: ci
  - package-ecosystem: "docker"
    directory: "/dockerfiles/k8s-code-generator/"
    open-pull-requests-limit: 100
    schedule:
      interval: "daily"
    target-branch: ci
  - package-ecosystem: "docker"
    directory: "/dockerfiles/pool-trigger-resource/"
    open-pull-requests-limit: 100
    schedule:
      interval: "daily"
    target-branch: ci
  - package-ecosystem: "docker"
    directory: "/dockerfiles/test-bitnami-ldap/"
    open-pull-requests-limit: 100
    schedule:
      interval: "daily"
    target-branch: ci
  - package-ecosystem: "docker"
    directory: "/dockerfiles/test-cfssl/"
    open-pull-requests-limit: 100
    schedule:
      interval: "daily"
    target-branch: ci
  - package-ecosystem: "docker"
    directory: "/dockerfiles/test-dex/"
    open-pull-requests-limit: 100
    schedule:
      interval: "daily"
    target-branch: ci
  - package-ecosystem: "docker"
    directory: "/dockerfiles/test-forward-proxy/"
    open-pull-requests-limit: 100
    schedule:
      interval: "daily"
    target-branch: ci
  - package-ecosystem: "docker"
    directory: "/dockerfiles/test-kubectl/"
    open-pull-requests-limit: 100
    schedule:
      interval: "daily"
    target-branch: ci
  - package-ecosystem: "docker"
    directory: "/pipelines/shared-helpers/test-binaries-image/"
    open-pull-requests-limit: 100
    schedule:
      interval: "daily"
    target-branch: ci
